# mysql 连接池配置
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
      file-size-threshold: 0
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${WWYT_MYSQL_USER_DEV:root}
      password: ${WWYT_MYSQL_PWD_DEV:123456}
      url: jdbc:mysql://${WWYT_MYSQL_HOST_DEV:wwyt-mysql}:${WWYT_MYSQL_PORT_DEV:3306}/${WWYT_MYSQL_DB_DEV:jt_prod}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: ${WWYT_REDIS_DB_DEV:0}
    host: ${WWYT_REDIS_HOST_DEV:wwyt-redis}
    port: ${WWYT_REDIS_PORT_DEV:6379}
    password: ${WWYT_REDIS_PWD_DEV:123456}
    timeout: 5000
    lettuce:
      pool:
        min-idle: 2
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000
# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  #    configuration:
  #      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.lyc.wwyt.config.handler
  show-sql: true
  meta-custom:
    del-flg: deleteMark
    create-name: createBy
    update-name: updateBy
  chine-rate: 1.5
  data-pms: true

swagger:
  title: 金坛五位一体接口文档
  description: 金坛五位一体上传平台
  version: 1.0
  securitySchemes:
    Authorization:
      type: http
      in: HEADER
      name: Authorization
      scheme: bearer

  servers:
    - url: http://127.0.0.1:7890
      description: 五位一体数据上传平台
springdoc:
  api-docs:
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.lyc.wwyt.controller
  # 配置需要生成接口文档的接口路径
  paths-to-match:
security:
  ignore-urls:
    - /v3/api-docs/**
    - /doc.html
    - /webjars/**
    - /druid/**
    - /configuration/ui
    - /swagger-resources/**
    - /js/**
    - /page/**
    - /css/**
    - /plugins/**
custom:
  aes-key: JTXCLYWWYTSJJKWD
  initialization-vector: JTXCLYWWYTSJJKWD
middle-table:
  tables:
    - t_aqfxfxdy
    - t_aqfxgkcs
    - t_aqfxsj
    - t_aqhdjl
    - t_aqhdxx
    - t_aqjcjl
    - t_aqpxjcjl
    - t_aqsczrclkxx
    - t_bjxxglxx
    - t_bqkzglxx
    - t_cbsglxx
    - t_cbspdglxx
    - t_cbssgglxx
    - t_cbswzjlxx
    - t_cbsxgzs
    - t_cbszysc
    - t_cbszyyjyasc
    - t_cgqxx
    - t_cgxx
    - t_ckqxx
    - t_cod_supply
    - t_dhzy
    - t_dhzy_aqcs
    - t_dhzy_qtfx
    - t_dhzy_splz
    - t_dict
    - t_dlzy
    - t_dlzy_aqcs
    - t_dlzy_splz
    - t_dtzy
    - t_dtzy_aqcs
    - t_dtzy_splz
    - t_dwjcxx
    - t_dwjzglxx
    - t_dwszxx
    - t_dwxbglxx
    - t_dzzy
    - t_dzzy_aqcs
    - t_dzzy_splz
    - t_fxsstxx
    - t_gczy
    - t_gczy_aqcs
    - t_gczy_splz
    - t_gjzzzdbwxx
    - t_gysglxx
    - t_jcbwhxx
    - t_jcpcsdxx
    - t_kfxx
    - t_log
    - t_lsydzy
    - t_lsydzy_aqcs
    - t_lsydzy_qtfx
    - t_lsydzy_splz
    - t_mbcdzy
    - t_mbcdzy_aqcs
    - t_mbcdzy_splz
    - t_pxhdxx
    - t_pxjg
    - t_pxjhxx
    - t_pxjyxgpjjl
    - t_pxzlxx
    - t_qtsbssxx
    - t_qyfxfbxx
    - t_qyjcxx
    - t_qyqyryxx
    - t_qyqyryxx_location
    - t_qyryxx
    - t_qzpxda
    - t_rypxxx
    - t_scqyxx
    - t_scssbfxx
    - t_scssbyxx
    - t_scsshfxx
    - t_scssjc1xx
    - t_scssjcxx
    - t_scsstyxx
    - t_scsswxxx
    - t_scssxx
    - t_sczzxx
    - t_shutdown_exam
    - t_sxkjzy
    - t_sxkjzy_aqcs
    - t_sxkjzy_qtfx
    - t_sxkjzy_splz
    - t_user
    - t_xmstsxx
    - t_yhpcjl
    - t_yhpcrwxx
    - t_yhzlxx
    - t_yjczkxx
    - t_yjdwglxx
    - t_yjwzglxx
    - t_yjyaglxx
    - t_yjyljhxx
    - t_yjylpjxx
    - t_zdwxyglxx
    - t_zycswxyshwpwxwhtxyzkxx
    - t_zyqyxx
xxl:
  job:
    admin:
      address: http://localhost:8080/xxl-job-admin/
      username: admin
      password: 123456
    executor:
      appname: xxl-job-executor-tt
      port: 9001
      logpath: /data/applogs/xxl-job/
      access-token: default_token
      auto-register: 0
